### ISSUE TITLE
convertschema hangs on OS X

### ISSUE THREAD

**Issue by BrendanSimon** [thesourcerer8/altium2kicad#10]
convertschema hangs on OS X (10.11.5).  I get the following output and nothing else.

    $ ~/Sandbox/altium2kicad/convertschema.pl 
    Handling TEST-PcbLib/Root Entry/FileHeader.dat

Is there something special that has to be done on OS X ?

**Comment by thesourcerer8** [comment]
I haven't tested it on OSX yet, I would assume that it should work too, but I can test in the next few days. But perhaps it is a problem with the file itself...

**Comment by thesourcerer8** [comment]
Please try again now, perhaps one of my fixes lately solved your problem.
