### ISSUE TITLE
`"` symbol in input file needs to be escaped in output

### ISSUE THREAD

**Issue by yorickdowne** [thesourcerer8/altium2kicad#114]
This KiCAD output because of a `.2" SCREW TERMINAL` reference:

```
(module ".2" SCREW TERMINAL" (layer F.Cu) (tedit 4289BEAB) (tstamp 539EEDBF)
```

Won't load because the `.2"` closes the opening `"`

Escaping the character works:

```
(module ".2\" SCREW TERMINAL" (layer F.Cu) (tedit 4289BEAB) (tstamp 539EEDBF)
```

**Comment by thesourcerer8** [comment]
Problem has been fixed, please update and try again.

**Comment by yorickdowne** [comment]
That fixed it, thank you!

I piled unto #111 with an issue where two `pts` are `0, 0`, and shouldn't be. Closing brackets are missing, and conversion shows errors at that point. I'll give you a new issue for it rather than clutter 111 further.

**Comment by thesourcerer8** [comment]
Thanks for the feedback!
