### ISSUE TITLE
Cannot open converted schematic from Altium 15

### ISSUE THREAD

**Issue by PigHillJimster** [thesourcerer8/altium2kicad#116]
Cannot open converted schematic from Altium 15 saved in Altium ascii format. Error from Kicad attached. Conversion log attached.

Is there a private area to submit the Altium file, please?

[altium2kicad-conversionlog.txt](https://github.com/thesourcerer8/altium2kicad/files/6295007/altium2kicad-conversionlog.txt)

[altium2kicad_errors_opening_converted_design_log.txt](https://github.com/thesourcerer8/altium2kicad/files/6294992/altium2kicad_errors_opening_converted_design_log.txt)

**Comment by thesourcerer8** [comment]
Please see my message on LinkedIn

**Comment by thesourcerer8** [comment]
Ah, I found the problem. You tried to open the file directly with kicad, and kicad tries to interpret it as a project file. You should open it with eeschema, that should work.

**Comment by PigHillJimster** [comment]
This issue is now closed. Thank you.
