### ISSUE TITLE
PC executable

### ISSUE THREAD

**Issue by daxliniere** [thesourcerer8/altium2kicad#132]
Is there a PC executable, either with GUI or at command line?

**Comment by thesourcerer8** [comment]
No, there is no GUI or commandline executable available. 
The KiCad developers have created their own Altium importer, which is included in newer KiCad versions now, which is based on the knowledge from this code, but I haven't tried it yet. There is also the online service which is linked from the README which you could use to upload your files and get them converted.

**Comment by daxliniere** [comment]
Thanks for your work, @thesourcerer8 !!
