### ISSUE TITLE
README would benefit from a screenshot

### ISSUE THREAD

**Issue by mithro** [thesourcerer8/altium2kicad#2]
A picture is worth a thousand words. It would be awesome to have a picture in the README showing a design in Altium and KiCad side by side.

**Comment by pgallir** [comment]
the readme looks very detailed at a first glance. 
but already at the second step  "Run FreeCAD, open and execute the macro step2wrl.FCMacro (it converts the step files to wrl)" it is not clear to me (who downloaded freecad just to use this tool on an existing altium project) how to run the freecad macro on what project. as a naive, I tried to call the macro with freecadcmd with no success... 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
jaky@jaky-Satellite-S55-A:/media/jaky/B9B0-99B8/SeLiNe_JR/SLN_JR___2kicad$ freecadcmd /usr/local/bin/altium2kicad-master/step2wrl.FCMacro 
FreeCAD 0.14, Libs: 0.14R2935 (Git)
(c) Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2011
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Exception while processing file: /usr/local/bin/altium2kicad-master/step2wrl.FCMacro [Cannot load Gui module in console application.]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

how should I proceed? thank you in advance.

**Comment by thesourcerer8** [comment]
Please open the FreeCAD GUI by starting freecad instead of freecadcmd, and there in the Macro->Macros.. Menu you should be able to start it.
Another solution is to use step2wrl instead of FreeCAD: https://github.com/twlostow/step2wrl

**Comment by diyjack** [comment]
Hi,
  Can't find any way to contact you. So ask here. 
  My Company has a similar job want to hire you to code or advisor, do you like to chat?  or 
  email  no.rich      @     yahoo.com
 Thanks. Hope  not disturb you.

**Comment by jacobrosenthal** [comment]
RE Freecad clarification
* File-Open->step2wrl.FCMacro
* edit ```for filename in glob.glob("Root Entry/Models/*.dat.step"):``` to be say ```for filename in glob.glob("/Users/jacobrosenthal/Desktop/nrf51x22_cdab/Root Entry/Models/*.dat.step"):```
* If it worked it dumped 0.wrl, 1.wrl etc files in the Root Entry directory, do a search and pull em all out

**Comment by thesourcerer8** [comment]
Screenshot has been finally added

**Comment by zekahh** [comment]
how do you take the altiumfile2kicad file, I don't get the instructions, I want to translate the pcb, and sch files,
I downloaded this https://github.com/thesourcerer8/altium2kicad in windows 7, does someone know how to proceed

cheers!

**Comment by thesourcerer8** [comment]
You would have to install a Perl interpreter, e.g. https://www.strawberryperl.com/ and run it then. If that is too complicated for you, you can also use the online service instead: http://www2.futureware.at/KiCad/ just pack it into a ZIP file and upload it there.
