### ISSUE TITLE
Power port labels are not translated

### ISSUE THREAD

**Issue by peabody124** [thesourcerer8/altium2kicad#4]
In my Altium schematic, the original file uses labeled power ports for different powers

![screen shot 2015-05-12 at 12 08 11 pm](https://cloud.githubusercontent.com/assets/618346/7593425/a9a2e20c-f89f-11e4-88d9-e282c3ca8533.png)

Unfortunately these are lost in the translation:
![screen shot 2015-05-12 at 12 08 22 pm](https://cloud.githubusercontent.com/assets/618346/7593426/abdd48b4-f89f-11e4-9b51-1f56d8408ee1.png)

Also if you look to the lower right all the parametric fields in the information block are lost and just put the values from altium without lookup: e.g. =sheetnumber

However, **AWESOME**work. This is amazing.

**Comment by thesourcerer8** [comment]
Please try again whether the new version solved this problem.

**Comment by peabody124** [comment]
Thank you very much! Much better.
![screen shot 2015-05-18 at 11 58 39 am](https://cloud.githubusercontent.com/assets/618346/7685654/5a0f720e-fd55-11e4-9b85-656a9e4b4b45.png)

It is nice to release OSHW in an OSS format.

**Comment by thesourcerer8** [comment]
Thanks for your feedback!
