### ISSUE TITLE
Double quotes coming from Altium need escaping.

### ISSUE THREAD

**Issue by jey5nd6** [thesourcerer8/altium2kicad#54]
https://github.com/thesourcerer8/altium2kicad/blob/e044347a1480d72a9575c57f474a68be2e552336/convertschema.pl#L498

**Comment by jey5nd6** [comment]
See: https://bugs.launchpad.net/kicad/+bug/1789099

**Comment by jey5nd6** [comment]
Oops.  I see the original poster to the Kicad bug database also posted here.  Feel free to delete these.

**Comment by thesourcerer8** [comment]
This is solved now. Thanks for forwarding it!
