### ISSUE TITLE
arcs are only exported when my $annotate=1;

### ISSUE THREAD

**Issue by cdwijs** [thesourcerer8/altium2kicad#59]
Hi All,
At work i design electronics with Altium designer. I just stumbled over Altium2Kicad. I've tried to convert a simple PCB with only 1 transistor. I noticed the arcs on the silkscreen were missing, but only when my $annotate=0; This patch solves this issue:

`
 convertpcb.pl | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/convertpcb.pl b/convertpcb.pl
index bd788f1..49fcf00 100755
--- a/convertpcb.pl
+++ b/convertpcb.pl
@@ -1117,7 +1117,7 @@ sub HandleArc($$$$) # $filename,$value,?,$data   (\%d,$data,$header,$line);
 		print OUT "#Arc#$_[3]: WARNING: width/2 exceeds radius*1.01 !\n" if($annotate);
 		$width=$r/2.0;
 	}
-    print OUT "  (gr_arc (start $x $y) (end $x1 $y1) (angle $angle) (layer $layer) (width $width))\n" if($annotate);
+    print OUT "  (gr_arc (start $x $y) (end $x1 $y1) (angle $angle) (layer $layer) (width $width))\n";
 	#print OUT "  (gr_text \"1\" (at $x1 $y1) (layer $layer))\n";
 	#print OUT "  (gr_text \"2\" (at $x2 $y2) (layer $layer))\n";
 	

`

**Comment by thesourcerer8** [comment]
Thanks a lot for reporting it, that bug got fixed!
