### ISSUE TITLE
Undefined subroutine &main::Sphere

### ISSUE THREAD

**Issue by jacobrosenthal** [thesourcerer8/altium2kicad#6]
convertpcb.pl gives Undefined subroutine &main::Sphere called at /Users/jacobrosenthal/Downloads/altium2kicad/convertpcb.pl line 1930.

Im not super familiar with perl, but I figured out that was presumably supposed to be a user defined function that never got written. In case anyone else runs into it and doesnt care about the 3d output, just comment out the line.

https://github.com/thesourcerer8/altium2kicad/blob/master/convertpcb.pl#L1930

**Comment by thesourcerer8** [comment]
Sorry, I have added the missing function now. If anyone has sample .PcbDoc files with Spheres in it, please provide them for testing.
