### ISSUE TITLE
STEP->VRML conversion

### ISSUE THREAD

**Issue by cbernardo** [thesourcerer8/altium2kicad#7]
As an alternative to a full FreeCAD installation, I would recommend using a tool which I created recently while experimenting to create a new 3D plugin for kicad:

https://github.com/cbernardo/kicad_oce_vis

Like Tom's conversion tool, which you currently use, this uses OpenCADCADE / OCE but the model traversal is more sophisticated so that even complex STEP assemblies will be rendered correctly.

**Comment by thesourcerer8** [comment]
Thanks a lot!

**Comment by thesourcerer8** [comment]
Could you perhaps provide precompiled (statically if possible) binaries?
