### ISSUE TITLE
convertschema.pl works but no .sch file produced

### ISSUE THREAD

**Issue by tyyao** [thesourcerer8/altium2kicad#72]
Hello altium2kicad creators and github community,

I ran the unpack.pl script and unpacked my .schdoc file into subdirectories. When I ran convertschema.pl, it did not convert the files in my subdirectories to .sch files. 
The screenshots below show the scripts being called to run in the command prompt and the subdirectories unpack.pl produced:
![perl_scripts_cmd_prompt](https://user-images.githubusercontent.com/33073657/56147813-90175400-5f6e-11e9-8a76-a711b88238cc.png)
![convertschema_script_dir](https://user-images.githubusercontent.com/33073657/56147816-93124480-5f6e-11e9-9c09-add03eec6b69.png)

As you can see, no .sch file was produced.
Could anyone please help me figure out if there is something I am doing incorrectly?

Many thanks,
tyyao

**Comment by thesourcerer8** [comment]
You have to run both commands in the same directory. convertschema.pl automatically looks for those subdirectories.

**Comment by tyyao** [comment]
Thank you so much thesourcerer8! (I like your name. It's cool) That did the trick, and now I have success converting altium schematics to kicad schematics.
