### ISSUE TITLE
Successful Conversion!

### ISSUE THREAD

**Issue by DPastl** [thesourcerer8/altium2kicad#74]
Hey, just wanted to say thank you for creating this awesome tool.  I was able to convert the atlium PCB files for the [SwiftNav Piksi Multi](https://www.swiftnav.com/resource-library?title=Piksi%20Multi%20Evaluation%20Board%20Design%20Files&product=Piksi%20Multi%20Evaluation%20Board&category=Design&release=latest) so that I could double check I had layouts and pinout correct (I didn't).  Saved me at least one spin of my design!

**Comment by thesourcerer8** [comment]
Thanks a lot for your feedback!
