### ISSUE TITLE
Does the converter actually work or what am I doing wrong?

### ISSUE THREAD

**Issue by epsilon-phi** [thesourcerer8/altium2kicad#81]
Hi,

first up - sorry for the bold question. I have been trying for some time to get the converter running but I am only getting bad results. I am new to github, so I hope this question is accepatble.

I am trying to convert a project that my university desperatly wants to have as a KiCad file. Trying to run the converter with it yields the following issues:
- The schematic is completely empty after saying is uses an old form of library list.
- In the layout the planes are there but only the perimeter is visible and it does not want to be filled in even after forcing with B.
- In the layout the component pads are circular instead of a rounded rectangle (which can be fixed by replacing to "rect" with a text editor)
- In the layout the vias have a drill diameter of 0.6ish instead of 0.3mm.

I have created a very small test project to hopefully solve these issues on my side myself but I am only getting the same issues, see the prictures for an explanation of the aforementioned points. Please find all my files attached. [TestPrj.zip](https://github.com/thesourcerer8/altium2kicad/files/4201651/TestPrj.zip) If it helps, I can gladly provide the big project as well.

![grafik](https://user-images.githubusercontent.com/61030782/74484693-5b8b6600-4eb9-11ea-9171-97694cd59b72.png)
![grafik](https://user-images.githubusercontent.com/61030782/74484728-71009000-4eb9-11ea-9198-8090a4dbcb61.png)
![grafik](https://user-images.githubusercontent.com/61030782/74484781-8fff2200-4eb9-11ea-8e6b-cc774f290dce.png)
![grafik](https://user-images.githubusercontent.com/61030782/74484819-a1e0c500-4eb9-11ea-86f0-d258b9fad916.png)

Could it be a version issue, so that the converter would only work with specific versions of Altium and KiCad, juding from the "old form of library list" message? Which versions of Altium and KiCad was this converter verified with?

I am still hoping to not have to redo my project entirely in KiCad again. Help is greatly appreciated.

Best regards
Phil

**Comment by thesourcerer8** [comment]
The fileformat of Alitum has changed, the schematic format has changed the parameter names from uppercase to mixedcase.
For me the filling works when i press "B".
The rectangular pads are a bit strange, perhaps the fileformat changed there as well, because the file seems to say that those have to be circles or ovals. Perhaps it is an oval with very sharp corners? Ovals are converted to circles by my converter at the moment. Can you please provide a test-file which contains all kinds of different shapes, together with screenshot how they look like, and perhaps text next to them that explains how they should look like? rectangular, oval, circle, ...
Can you please explain the drill diameter with larger screenshots and marking them? I am not used to drill diameters.

**Comment by thesourcerer8** [comment]
Could you please correct the drill diameter in the KiCad file and send me both original and corrected file?

**Comment by epsilon-phi** [comment]
Okay sure, I'll try my best.

So here is the test-file:
2D Altium:
![shapes-altium](https://user-images.githubusercontent.com/61030782/75805108-76971a80-5d81-11ea-8729-5b79e35b6c59.png)
2D KiCad:
![shapes-kicad](https://user-images.githubusercontent.com/61030782/75805133-80208280-5d81-11ea-918e-3f6814034416.png)
3D Altium:
![shapes-altium3d](https://user-images.githubusercontent.com/61030782/75805159-90d0f880-5d81-11ea-81bf-ef384cf47ae7.png)
It seems that octagonal and rounded rectangle pads are both getting converted into round (=circle) pads. Slots are being converted to rounds (fair enough). For some strange reasons NPTH pads are not selectable in KiCad and they are shown only halfway through in the 3D view. 
Altium drills:
![drills](https://user-images.githubusercontent.com/61030782/75805794-c2968f00-5d82-11ea-9ea7-46a4b55aecc1.png)
KiCad drills:
![drills-kicad](https://user-images.githubusercontent.com/61030782/75805806-c7f3d980-5d82-11ea-83d4-80cb21d1cfd7.png)
As for the vias, same picture as before: where the drill diameter should be 0.3, its 0.6 (mm). The via pad however is correct (see pictures). I discovered that the KiCad via description lines simply miss "(drill 0.3)". Maybe this will already fix the issue.
![drills-text](https://user-images.githubusercontent.com/61030782/75805828-d3470500-5d82-11ea-9075-3367fb086ea2.png)
Here is a zip will all the files including pictures: [a2k-shapestest.zip](https://github.com/thesourcerer8/altium2kicad/files/4282889/a2k-shapestest.zip)

Do you have any ideas on the schematic yet?

**Comment by thesourcerer8** [comment]
Ok, I have updated the convertschema.pl to handle the new file format. Thanks a lot for the test-files! I have added a rounded rectangle handling now, since KiCad is able to handle them now too. Can Altium define the percentage of roundedness? Could you please provide a test-file with various different "regions"? Triangles, rectangular, ...   and please have a bit more space between the different objects. I still have to investigate the drill issue.

**Comment by epsilon-phi** [comment]
Oh this is great news. Thank you so much for your support, I appreciate it a lot!

Yes, Altium can define the percentage of roundness. Together with some regions and polygons, pads with different "roundnesses" are included in the new test file: 
[a2k-test2.zip](https://github.com/thesourcerer8/altium2kicad/files/4294790/a2k-test2.zip)
In Altium you see:
![test2-altium](https://user-images.githubusercontent.com/61030782/76018006-d9261d00-5f1f-11ea-94b3-7272d8b678a5.png)
or in 3D:
![test2-altium3D](https://user-images.githubusercontent.com/61030782/76018011-dd523a80-5f1f-11ea-9768-b76e5a08366a.png)
In KiCad after the conversion you find:
![test2-kicad](https://user-images.githubusercontent.com/61030782/76018056-ec38ed00-5f1f-11ea-8a1a-cec1810a09a2.png)

I'll stay curious about how all this will come out. I'll also gladly provide more test data, if you should require so.

**Comment by epsilon-phi** [comment]
After checking you latest revision of the schematic converter I found it looks much better now. All the Footprints now get imported correctly and the traces and sheet entries and even the references to other sheets are there. Only the Power & Ground Net-Symbols are still missing and being shown as ??-Boxes, however thats nothing you cant fix by hand. Thanks for the amazing work!
![grafik](https://user-images.githubusercontent.com/61030782/76019566-36bb6900-5f22-11ea-879b-8441d9d71310.png)

**Comment by epsilon-phi** [comment]
> Only the Power & Ground Net-Symbols are still missing and being shown as ??-Boxes, however thats nothing you cant fix by hand.

I just re-read on the main page here, that this limitation is known. In that case, it seems like the converter does now do exactly what it should do. :D

**Comment by thesourcerer8** [comment]
For me it worked once to just save the file, close pcbnew and open it again, and the symbols were there. Perhaps the converter does something wrong in the fileformat, I'll investigate ...

**Comment by thesourcerer8** [comment]
Ok, I updated to the new kicad schematic fileformat, which solved the power symbols now.

**Comment by thesourcerer8** [comment]
I added handling for the rectangle roundings now.

**Comment by thesourcerer8** [comment]
The regions are converting to zones now.

**Comment by thesourcerer8** [comment]
I removed the paste layer now which covered the holes

**Comment by epsilon-phi** [comment]
Okay I tested it today and my power symbols are still missing. But I rather belive that this has to do with my KiCad Version or something like this as I just cant get the polygons - which are there - to fill (<- definitely a KiCad error).
As my original problem, that the converter did not do anything at all, has been solved now, I will close this thread and investigate a bit further on my side. Thanks a lot for your effort to adjust all these details in the process. Keep up the amazing work! Greetings

**Comment by pointhi** [comment]
@epsilon-phi 

Thanks for your testfiles. I tried them with my importer which will be soon integrated into KiCad:

* https://gitlab.com/kicad/code/kicad/-/merge_requests/60

It seems most things work, except: rotated slot hole,  rectangular hole and rounded zones. But those three things are not supported in KiCad and would need to be emulated anyways.

![regionsround](https://user-images.githubusercontent.com/1652144/77828598-b9e46f00-711c-11ea-94be-64ee6d4136d5.png)
![shapes](https://user-images.githubusercontent.com/1652144/77828601-bcdf5f80-711c-11ea-993b-717dc882f0a2.png)
